config/routes.rb
WebexApp::Application.routes.draw do
  resources :products

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resources :users, :only => :show
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :price
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h3>Users</h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_navigation.html.erb
<%= link_to "WebEx App", root_path, :class => 'brand' %>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<div class="nav-collapse">

    <ul class="nav">
        <% if user_signed_in? %>
            <li>
                <%= link_to('Logout', destroy_user_session_path, :method => 'delete') %>
            </li>
        <% else %>
            <li>
                <%= link_to('Login', new_user_session_path) %>
            </li>
        <% end %>
        <% if user_signed_in? %>
            <li>
                <%= link_to('Edit account', edit_user_registration_path) %>
            </li>
            <li>
                <%= link_to "Products", products_path %>
            </li>
        <% else %>
            <li>
                <%= link_to('Sign up', new_user_registration_path) %>
            </li>
        <% end %>
    </ul>
    <form class="navbar-search pull-left">
        <input type="text" class="search-query" placeholder="Search">
    </form>
    <ul class="nav">
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Dropdown <b class="caret"></b></a>

            <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li><a href="#">Separated link</a></li>
            </ul>

        </li>

    </ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "WebEx App" %></title>
    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode/svn/trunk/html5.js" type="text/javascript"></script>
      <![endif]-->
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield(:head) %>
</head>
<body>
<div class="container">
    <div class="navbar navbar-fixed-top">
        <nav class="navbar-inner">
            <div class="container">
                <%= render 'layouts/navigation' %>
            </div>
        </nav>
    </div>
    <div id="main" role="main">
        <div class="container">
            <div class="content">
                <div class="row">
                    <div class="span9">
                        <% flash.each do |name, msg| %>
                            <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
                                <a class="close" data-dismiss="alert">×</a>
                                <%= msg %>
                            </div>
                        <% end %>
                        <%= yield %>
                    </div>

                    <div class="span3">
                        <h2>About App</h2>

                        <p>Twitter’s Bootstrap helps you build beautiful web apps quickly. It provides a variety of CSS
                            and JavaScript for making layouts, navigation, forms and a lot more and it even includes
                            support for responsive web design. As an example, if you visit its homepage and alter the
                            width of the browser window the page layout will change to best fit that width. This can
                            really improve the experience of using web applications on mobile devices.</p>
                    </div>

                </div>
            </div>
        </div>
        <!--! end of .container -->
    </div>

    <hr>
    <footer>
        <p>&copy; CTI 2012</p>
    </footer>
</div>
</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
        <legend><%= controller.action_name.capitalize %> Product</legend>

        <%= f.input :name %>
        <%= f.input :price %>

        <div class="form-actions">
            <%= f.submit nil, :class => 'btn btn-primary' %>
            <%= link_to 'Cancel', products_path, :class => 'btn' %>
        </div>
    </fieldset>
<% end %>

app/views/products/edit.html.erb
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#1" data-toggle="tab">Products</a></li>
        <li><a href="#2" data-toggle="tab">Section 2</a></li>
        <li><a href="#3" data-toggle="tab">Section 3</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="1">
            <h1>Products</h1>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created at</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                <% @products.each do |product| %>
                    <tr>
                        <td><%= product.id %></td>
                        <td><%= link_to product.name, product_path(product) %></td>
                        <td><%= product.created_at %></td>
                        <td>
                            <%= link_to 'Edit', edit_product_path(product), :class => 'btn btn-mini' %>
                            <%= link_to 'Destroy', product_path(product), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
                        </td>
                    </tr>
                <% end %>
                </tbody>
            </table>

            <%= link_to 'New', new_product_path, :class => 'btn btn-primary' %>
        </div>

        <div class="tab-pane" id="2">


            <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1
                labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft
                beer
                twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl
                cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS
                salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit,
                sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester
                stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
        </div>

        <div class="tab-pane" id="3">


            <p>Bring your tabs to life with a simple plugin to toggle between content via tabs. Bootstrap integrates
                tabbable tabs in four styles: top (default), right, bottom, and left.

                Changing between them is easy and only requires changing very little markup.</p>
        </div>

    </div>
</div>

app/views/products/new.html.erb
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<h1>Product</h1>

<p>
  <b>Name</b><br>
  <%= @product.name %>
</p>

<p>
  <b>Price</b><br>
  <%= @product.price %>
</p>

<div class="form-actions">
  <%= link_to 'Back', products_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_product_path(@product), :class => 'btn' %>
  <%= link_to 'Delete', product_path(@product), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>